# Generated by Django 3.1.7 on 2021-02-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotidyToken',
            new_name='SpotifyToken',
        ),
    ]
